to_do_list/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("todo_app.urls", namespace="todo_app" )),
]

todo_app/urls.py
from django.urls import path
from todo_app.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    switch_is_done,
)


urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path('task/<int:pk>/switch/', switch_is_done, name="task-switch"),
]


app_name = "todo_app"

todo_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-created_at"]

todo_app/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from todo_app.models import Task, Tag


class TaskListView(generic.ListView):
    queryset = Task.objects.prefetch_related("tags")
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_app:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_app:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_app:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_app:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_app:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_app:tag-list")


def switch_is_done(request, pk):
    task = Task.objects.get(pk=pk)
    if task.is_done:
        task.is_done = False
    else:
        task.is_done = True
    task.save()
    return redirect("todo_app:task-list")

templates/base.html
<!DOCTYPE "html">
<html lang="en">
<head>
  {% block title %}
    <title>Todo list</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a href="{% url "todo_app:task-list" %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url "todo_app:tag-list" %}">Tags</a>
  </li>
</ul>

templates/todo_app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag form</h1>
  <p>Are you sure you want to delete this tag: {{ tag }}?</p>
  <form action="" method="post">
    {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  <a href="{% url "todo_app:tag-list" %}" class = "btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_app/tag_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Tag </h1>
  <form action="" method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
  <input class ="btn btn-primary" type="submit" value="Submit">
  <a href="{% url "todo_app:tag-list" %}" class = "btn btn-secondary">Cancel</a>
  </form>

{% endblock %}

templates/todo_app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div style="display: flex; justify-content: space-between; align-items: center;">
    <h1 style="margin: 0;"> Tags </h1>
    <a href = "{% url "todo_app:tag-create" %}" class = "btn btn-primary">Add</a>
  </div>
  <br>
  {% if tag_list %}
    <table class = "table">

      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
    <tr>
      <td>{{ tag.name }}</td>
      <td><a href="{% url "todo_app:tag-update" pk=tag.id %}" class = "btn btn-secondary">Update</a></td>
      <td><a href="{% url "todo_app:tag-delete" pk=tag.pk %}" class = "btn btn-secondary">Delete</a></td>
    </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>No tags in list</p>
  {% endif %}
{% endblock %}

templates/todo_app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task form</h1>
  <p>Are you sure you want to delete this task: {{ task }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    <a href="{% url "todo_app:task-list" %}" class = "btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_app/task_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Task </h1>
  <form action="" method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
  <input class ="btn btn-primary" type="submit" value="Submit">
  <a href="{% url "todo_app:task-list" %}" class = "btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_app/task_list.html
{% extends "base.html" %}

{% block content %}
  <div style="display: flex; justify-content: space-between; align-items: center; padding-bottom: 20px;">
    <h1 style="margin: 0;">TODO list</h1>
    <a href="{% url "todo_app:task-create" %}" class="btn btn-primary">Add task</a>
  </div>


  {% for task in task_list %}
    <div>
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <span style="font-weight: bold; font-size: 1.2em;">
          {{ task.content }}
          {% if task.is_done %}
            <span style="color: green"> Done </span>
          {% else %}
            <span style="color: red"> Not done </span>
          {% endif %}
        </span>
        <span>
          {% if task.is_done %}
            <a href="{% url 'todo_app:task-switch' task.id %}" class="btn btn-secondary">Undo</a>
          {% else %}
            <a href="{% url 'todo_app:task-switch' task.id %}" class="btn btn-success">Complete</a>
          {% endif %}
        </span>
      </div>

      <p>
        Created: {{ task.created_at }}
        {% if task.deadline %}
          <span style="color: red">Deadline: {{ task.deadline }}</span>
        {% endif %}
      </p>

      <p>
        <span style="font-size: 1.1em; color: grey">Tags:
          {% for tag in task.tags.all %}
            {{ tag }}
          {% empty %}
            No tag yet
          {% endfor %}
        <a href="{% url "todo_app:task-update" task.id %}">Update</a>
        <a href="{% url "todo_app:task-delete" task.id %}">Delete</a>
        </span>
      </p>

      <hr style="border: none; height: 2px; background-color: darkgray;">
    </div>
  {% empty %}
    <p>No tasks in list</p>
  {% endfor %}
{% endblock %}